disabled_rules:
  - colon
  - syntactic_sugar
  - identifier_name
  - opening_brace
  - nesting
  - empty_enum_arguments
  - trailing_newline
  - trailing_whitespace
  - function_body_length
  - vertical_whitespace
  - for_where
  - unused_closure_parameter
  - redundant_string_enum_value
  - duplicate_imports
  - trailing_semicolon
  - cyclomatic_complexity
  - trailing_comma
  - switch_case_alignment
  - type_name
  - line_length
  - unused_optional_binding

included: # 执行 linting 时包含的路径。如果出现这个 `--path` 会被忽略。
  - SWHub

excluded: # 执行 linting 时忽略的路径。 优先级比 `included` 更高。
  - Pods
  - SWHub/R.generated.swift

line_length: 300
