disabled_rules:
    - force_try
    - nesting

included:
    - SWHub

excluded:
    - Pods
    - SWHub/R.generated.swift

line_length:
    - 300
    - 400

type_body_length:
    - 300
    - 400

function_body_length:
    - 300
    - 400

type_name:
    min_length: 3
    max_length:
        warning: 40
        error: 50
    excluded:
        - T
        - E

identifier_name:
    min_length:
        error: 3
    excluded:
        - i
        - x
        - y
        - id
        - vc
        - in
        - kf
        - bg
        - fg
